name: CI

on: [push, pull_request, release]

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Ensures all refs and tags are fetched so "git describe --always" is working as expected
          fetch-depth: 0

      # A workaround for annotated tags with actions/checkout@v2
      # see https://github.com/actions/checkout/issues/290
      - name: Fetch Tags correctly
        run: git fetch --force --tags

      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: |
          ./gradlew check jibDockerBuild -x bootJar

      - name: Prepare cache
        run: |
          rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
          rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      - name: Authenticate to GitHub Docker Registry
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          docker logout
          # "Username" can be anything as we are authenticating via the default workflow access token!
          # See https://github.com/actions/starter-workflows/issues/66
          echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy master as latest
        if: github.ref == 'refs/heads/master'
        # This weird expression converts the repository name to lowercase
        # https://github.community/t/additional-function-s-lowercase-uppercase/140632/2
        run: |
          export DOCKER_REPO="${GITHUB_REPOSITORY,,}"
          docker push ghcr.io/${DOCKER_REPO}